import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import LoadingOverlay from "@/components/loading-overlay";
import "@fortawesome/fontawesome-svg-core/styles.css"; // Import the styles manually
import { config } from "@fortawesome/fontawesome-svg-core";
config.autoAddCss = false;

const roboto = Roboto({ subsets: ["vietnamese"] });

export const metadata: Metadata = {
  title: "Bus Booking",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
    shortcut: "/favicon.ico",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} h-dvh overflow-hidden`}>
        <Toaster richColors position="top-right" />
        <LoadingOverlay />
        {children}
      </body>
    </html>
  );
}
